# Setup
title: TIL
email: peter@labwire.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
tagline: A daily archive of stuff I’ve learned.
baseurl: "/til"
url: ""
twitter_username: peterhry
github_username:  peterhry
paginate: 1

# About/contact
author:
  name: Peter Hrynkow
  url: http://peterhrynkow.com

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

