# Setup
title: peterhrynkow.com
email: peter@labwire.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
tagline: Peter writes code and words about code.
# baseurl: "/peterhrynkow.com"
url: ""
twitter_username: peterhry
github_username:  peterhry

# About/contact
author:
  name: Peter Hrynkow
  url: http://peterhrynkow.com
  github: https://github.com/peterhry
  stackoverflow: https://stackoverflow.com/users/1345271/peterhry
  linkedin: http://ca.linkedin.com/pub/peter-hrynkow/20/a90/580
  codepen: https://codepen.io/peterhry
  twitter: https://twitter.com/peterhry
#Others
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

